sudo: required
dist: trusty

language: cpp

compiler:
    - gcc
    - clang

install:
    # Install Pacman dependencies
    - sudo apt-get install libsfml-dev -y
    - sudo apt-get install libjansson-dev -y

    # Install STP dependencies
    - sudo apt-get install libpugixml-dev -y
    - sudo apt-get install zlib1g-dev -y

script: cmake . && make
